"""Exact small-width audit for the same-width Fredkin circuit group.

This diagnostic is deliberately separate from the Lean proof.  It enumerates
the finite group generated by adjacent structural wire swaps and every
placement of the paper's zero-controlled Fredkin gate.  Exhaustive closure is
practical through width four and establishes that the width-four obstruction
proved in ``Completeness/NoAncilla.lean`` is the first one at these widths.

The script has no third-party dependencies.  A permutation is represented by
its complete image tuple, so membership and group size are exact rather than
sampled.
"""

from collections import deque
from math import comb, factorial, prod


Permutation = tuple[int, ...]


def swap_bits(state: int, first: int, second: int) -> int:
    """Exchange two bit coordinates of an integer-encoded Boolean state."""
    if ((state >> first) & 1) != ((state >> second) & 1):
        state ^= (1 << first) | (1 << second)
    return state


def wire_swap(width: int, first: int, second: int) -> Permutation:
    """Complete-state action of one structural coordinate transposition."""
    return tuple(
        swap_bits(state, first, second) for state in range(1 << width)
    )


def fredkin(width: int, control: int, first: int, second: int) -> Permutation:
    """Complete-state action of the paper's zero-controlled Fredkin gate."""
    return tuple(
        swap_bits(state, first, second)
        if ((state >> control) & 1) == 0
        else state
        for state in range(1 << width)
    )


def generators(width: int) -> list[Permutation]:
    """Generators available from the repository grammar at fixed width."""
    result = [wire_swap(width, i, i + 1) for i in range(width - 1)]
    for control in range(width):
        data = [index for index in range(width) if index != control]
        for offset, first in enumerate(data):
            for second in data[offset + 1 :]:
                result.append(fredkin(width, control, first, second))
    return result


def compose(left: Permutation, right: Permutation) -> Permutation:
    """Return ``left`` after ``right``."""
    return tuple(left[right[state]] for state in range(len(left)))


def generated_group(width: int) -> set[Permutation]:
    """Exhaustively close the fixed-width generators under composition."""
    identity = tuple(range(1 << width))
    basis = generators(width)
    seen = {identity}
    frontier = deque([identity])
    while frontier:
        current = frontier.popleft()
        for generator in basis:
            candidate = compose(generator, current)
            if candidate not in seen:
                seen.add(candidate)
                frontier.append(candidate)
    return seen


def conservative_group_order(width: int) -> int:
    """Order of the product of symmetric groups on all Hamming layers."""
    return prod(factorial(comb(width, weight)) for weight in range(width + 1))


def middle_layer_swap() -> Permutation:
    """Swap 1100 and 1010 only (integer states 3 and 5 in this encoding)."""
    image = list(range(16))
    image[3], image[5] = image[5], image[3]
    return tuple(image)


def main() -> None:
    expected = {
        1: (1, 1),
        2: (2, 2),
        3: (36, 36),
        4: (207_360, 414_720),
    }
    groups: dict[int, set[Permutation]] = {}
    for width in range(1, 5):
        group = generated_group(width)
        groups[width] = group
        generated = len(group)
        full = conservative_group_order(width)
        assert (generated, full) == expected[width]
        assert full % generated == 0
        print(
            f"width {width}: generated={generated} full={full} "
            f"index={full // generated}"
        )

    target = middle_layer_swap()
    assert target not in groups[4]
    assert target[3] == 5 and target[5] == 3
    assert all(
        state.bit_count() == target[state].bit_count() for state in range(16)
    )
    print("width 4 target 1100<->1010: conservative=yes generated=no")


if __name__ == "__main__":
    main()
