import ConservativeLogic.State.Core

/-!
# Deterministic discrete-time machines

This module gives total deterministic transition systems over fixed-width
Boolean state, input, and output registers.  Time is discrete and
initialization is explicit: `Run.state t` is the stored state immediately
before tick `t`, `input t` is consumed and `Run.output t` is observed during
that tick, and the transition returns `Run.state (t + 1)`.

The semantics contains no same-time feedback equation or fixed-point choice.
Its prefix-agreement theorems make causality explicit.
-/

namespace ConservativeLogic.Sequential

/-- A width-`w` Boolean signal sampled at natural-numbered ticks. -/
abbrev Signal (w : Nat) := Nat → BitState w

namespace Signal

/-- Two signals agree at every tick strictly before `bound`. -/
def AgreeBefore {w : Nat} (bound : Nat) (left right : Signal w) : Prop :=
  ∀ time, time < bound → left time = right time

/-- Two signals agree through `bound`, including the sample at `bound`. -/
def AgreeThrough {w : Nat} (bound : Nat) (left right : Signal w) : Prop :=
  ∀ time, time ≤ bound → left time = right time

/-- Agreement through a tick is agreement before its successor. -/
theorem agreeThrough_iff_agreeBefore_succ {w : Nat} (bound : Nat)
    (left right : Signal w) :
    AgreeThrough bound left right ↔ AgreeBefore (bound + 1) left right := by
  constructor
  · intro agree time before
    exact agree time (Nat.lt_succ_iff.mp before)
  · intro agree time through
    exact agree time (Nat.lt_succ_iff.mpr through)

end Signal

/-- A total deterministic tick from stored state and input to next state and output. -/
structure Machine (stateWidth inputWidth outputWidth : Nat) where
  tick : BitState stateWidth → BitState inputWidth →
    BitState stateWidth × BitState outputWidth

/-- The state and output signals generated by a machine. -/
structure Run {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth) where
  state : Signal stateWidth
  output : Signal outputWidth

namespace Run

/-- Extensionality for runs, stated without exposing their constructor. -/
theorem ext_state_output {stateWidth inputWidth outputWidth : Nat}
    {machine : Machine stateWidth inputWidth outputWidth} {left right : Run machine}
    (state_eq : left.state = right.state) (output_eq : left.output = right.output) :
    left = right := by
  cases left
  cases right
  cases state_eq
  cases output_eq
  rfl

end Run

namespace Machine

/-- The recursively determined stored state immediately before each tick. -/
def runState {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (input : Signal inputWidth) :
    Signal stateWidth
  | 0 => initial
  | time + 1 => (machine.tick (machine.runState initial input time) (input time)).1

/-- Execute a machine from an explicit initial state on an input signal. -/
def run {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (input : Signal inputWidth) : Run machine where
  state := machine.runState initial input
  output time := (machine.tick (machine.runState initial input time) (input time)).2

@[simp]
theorem runState_zero {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (input : Signal inputWidth) :
    machine.runState initial input 0 = initial := rfl

@[simp]
theorem runState_succ {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (input : Signal inputWidth) (time : Nat) :
    machine.runState initial input (time + 1) =
      (machine.tick (machine.runState initial input time) (input time)).1 := rfl

@[simp]
theorem run_state_zero {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (input : Signal inputWidth) :
    (machine.run initial input).state 0 = initial := rfl

@[simp]
theorem run_tick {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (input : Signal inputWidth) (time : Nat) :
    machine.tick ((machine.run initial input).state time) (input time) =
      ((machine.run initial input).state (time + 1),
        (machine.run initial input).output time) := by
  rfl

/-- Relational characterization of a run by its initialization and tick equations. -/
def IsTrace {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (input : Signal inputWidth)
    (candidate : Run machine) : Prop :=
  candidate.state 0 = initial ∧
    ∀ time, machine.tick (candidate.state time) (input time) =
      (candidate.state (time + 1), candidate.output time)

/-- Recursive execution satisfies the trace equations. -/
theorem run_isTrace {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (input : Signal inputWidth) :
    machine.IsTrace initial input (machine.run initial input) := by
  constructor
  · rfl
  · intro time
    rfl

/-- The initialization and transition equations determine a unique complete run. -/
theorem trace_unique {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (input : Signal inputWidth)
    (candidate : Run machine) (valid : machine.IsTrace initial input candidate) :
    candidate = machine.run initial input := by
  have state_eq : candidate.state = (machine.run initial input).state := by
    funext time
    induction time with
    | zero => exact valid.1
    | succ time ih =>
        have candidate_tick := congrArg Prod.fst (valid.2 time)
        have canonical_tick := congrArg Prod.fst (machine.run_tick initial input time)
        rw [ih] at candidate_tick
        exact candidate_tick.symm.trans canonical_tick
  apply Run.ext_state_output state_eq
  funext time
  have candidate_tick := congrArg Prod.snd (valid.2 time)
  have canonical_tick := congrArg Prod.snd (machine.run_tick initial input time)
  rw [state_eq] at candidate_tick
  exact candidate_tick.symm.trans canonical_tick

/-- A trace exists uniquely for every initial state and complete input signal. -/
theorem existsUnique_trace {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (input : Signal inputWidth) :
    ∃! candidate : Run machine, machine.IsTrace initial input candidate := by
  refine ⟨machine.run initial input, machine.run_isTrace initial input, ?_⟩
  intro candidate valid
  exact machine.trace_unique initial input candidate valid

/-- State at tick `time` consults only input samples strictly before `time`. -/
theorem runState_eq_of_agreeBefore {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (left right : Signal inputWidth) (time : Nat)
    (agree : Signal.AgreeBefore time left right) :
    machine.runState initial left time = machine.runState initial right time := by
  induction time with
  | zero => rfl
  | succ time ih =>
      rw [machine.runState_succ initial left time,
        machine.runState_succ initial right time]
      rw [ih (fun index before =>
        agree index (Nat.lt_trans before (Nat.lt_succ_self time)))]
      rw [agree time (Nat.lt_succ_self time)]

/-- The stored component of a run is causal with a strict input-prefix bound. -/
theorem run_state_eq_of_input_eq_before {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (left right : Signal inputWidth) (time : Nat)
    (agree : Signal.AgreeBefore time left right) :
    (machine.run initial left).state time = (machine.run initial right).state time :=
  machine.runState_eq_of_agreeBefore initial left right time agree

/-- Output at tick `time` consults input samples only through tick `time`. -/
theorem run_output_eq_of_input_eq_through {stateWidth inputWidth outputWidth : Nat}
    (machine : Machine stateWidth inputWidth outputWidth)
    (initial : BitState stateWidth) (left right : Signal inputWidth) (time : Nat)
    (agree : Signal.AgreeThrough time left right) :
    (machine.run initial left).output time =
      (machine.run initial right).output time := by
  change
    (machine.tick (machine.runState initial left time) (left time)).2 =
      (machine.tick (machine.runState initial right time) (right time)).2
  rw [machine.runState_eq_of_agreeBefore initial left right time
    (fun index before => agree index (Nat.le_of_lt before))]
  rw [agree time (Nat.le_refl time)]

end Machine

end ConservativeLogic.Sequential
